function partialfpartialshimfourier = calcpartialBpartialShimFourier(...
    partialfpartialBz, opt, wv, nn )

% FBshim_nn = wv.FBshim( nn, : );

partialfpartialshimfourier =...
    partialfpartialBz .* reshape(...
    wv.FBshim( nn, : ) .* reshape( wv.bzsens, [ opt.numPos, 1, opt.numZCoils ] ),...
    [ opt.numPos, 1, opt.numFourier_shim * opt.numZCoils ] );

end