function partialfpartialgradfourier = calcpartialBpartialGradFourier(...
    partialfpartialBz, opt, wv, nn )

% FBgrad_nn = wv.FBgrad( nn, : );

partialfpartialgradfourier =...
    partialfpartialBz .* reshape(...
    wv.FBgrad( nn, : ) .* reshape( wv.pos, [ opt.numPos, 1, 3 ] ),...
    [ opt.numPos, 1, opt.numFourier_grad * 3 ] );

end