function ddGxyzdtdparam = ddGxyzdtdparam_fn( t, s )

%% Initialize derivatives
t = t( : ).';

indenom = indenom_fn( t, s );
indenomsq = indenomsq_fn( t, s );
denom = denom_fn( t, s );
kr = kr_fn( t, s );
ktheta = ktheta_fn( t, s );
kphi = kphi_fn( t, s );
sinktheta = sin( ktheta );
cosktheta = cos( ktheta );
sinkphi = sin( kphi );
coskphi = cos( kphi );
dkrdt = dkrdt_fn( t, s );
d2krdt2 = d2krdt2_fn( t, s );
dkthetadt = dkthetadt_fn( t, s );
dkphidt = dkphidt_fn( t, s );
dsinkthetadt = dkthetadt .* cos( ktheta );
d2sinkthetadt2 = ( - dkthetadt.^2 ) * sinktheta;
dcoskthetadt = -dkthetadt .* sin( ktheta );
d2coskthetadt2 = ( - dkthetadt.^2 ) * cosktheta;
dsinkphidt = dkphidt .* coskphi;
d2sinkphidt2 = ( - dkphidt.^2 ) .* sinkphi;
dcoskphidt = -dkphidt .* sinkphi;
d2coskphidt2 = ( - dkphidt.^2 ) .* coskphi;

% kmax
dd2krdt2dkmax = ( ( s.a.^2 * indenom ) .* ( indenom - 1 ) ) ./ ( s.T^2 * denom.^3 );
ddkrdtdkmax = ( -s.a .* indenom ) ./ ( s.T .* denom.^2 );
dkrdkmax = 1 ./ denom;

% a
dd2krdt2da = ( ( ( s.a * s.kmax ) * indenom ) ./ ( s.T^3 * denom.^4 ) )...
    .* (...
    ( ( 4 * s.a ) * t ) .* indenom...
    - s.a * t .* indenomsq...
    - ( 4 * s.a * s.b * s.T ) * indenom...
    + ( s.a * s.b * s.T ) * indenomsq...
    + ( 2 * s.T ) * indenomsq...
    + ( s.a * s.b * s.T ) - s.a * t - 2 *s.T );
ddkrdtda = - ( ( 1 ) ./ ( s.T^2 * denom.^3 ) )...
    .* ( ( s.kmax * indenom ) .*...
    ( ( -s.a * t ) .* indenom ...
    + ( s.a * s.b * s.T ) * indenom...
    + s.T * indenom ...
    - ( s.a * s.b * s.T ) + s.a * t + s.T ) );
dkrda = ( -s.kmax * ( ( t/s.T - s.b ) .* indenom ) ) ./ ( denom.^2 );

% b
dd2krdt2db = ( ( ( s.a^3 * s.kmax ) * indenom ) ./ ( s.T^2 * denom.^4 ) ) .*...
    ( -4 * indenom + indenomsq + 1 );
ddkrdtdb = ( ( - s.a^2 * s.kmax ) * ( indenom .* ( indenom - 1 ) ) ) ./ ( s.T * denom.^3 );
dkrdb = ( ( s.kmax * s.a ) .* indenom ) ./ ( denom.^2 );

% u
dsinkthetadu = t .* cos( ktheta );
ddsinkthetadtdu = cosktheta - s.u * ( t .* sinktheta );
dd2sinkthetadt2du = - s.u * ( 2 * sinktheta + s.u * ( t .* cosktheta )  );

dcoskthetadu = -t .* sin( ktheta );
ddcoskthetadtdu = - sinktheta - s.u * ( t .* cosktheta );
dd2coskthetadt2du = s.u * ( s.u * ( t .* sinktheta ) - 2 * cosktheta );

% v
dsinkphidv = t .* coskphi;
ddsinkphidtdv = coskphi - s.v * ( t .* sinkphi );
dd2sinkphidt2dv = -s.v * ( 2 * sinkphi + s.v * ( t .* coskphi ) );

dcoskphidv = -t .* sinkphi;
ddcoskphidtdv = - sinkphi - s.v * ( t .* coskphi );
dd2coskphidt2dv = s.v * ( s.v * ( t .* sinkphi ) - 2 * coskphi );

dd2kxyzdt2dparam = zeros( 3, length( t ), 5 );

%% partial kmax
dd2kxdt2dkmax = ...
    dd2krdt2dkmax .* sinktheta .* coskphi + ddkrdtdkmax .* dsinkthetadt .* coskphi + ddkrdtdkmax .* sinktheta .* dcoskphidt +...
    ddkrdtdkmax .* dsinkthetadt .* coskphi + dkrdkmax .* d2sinkthetadt2 .* coskphi + dkrdkmax .* dsinkthetadt .* dcoskphidt +...
    ddkrdtdkmax .* sinktheta .* dcoskphidt + dkrdkmax .* dsinkthetadt .* dcoskphidt + dkrdkmax .* sinktheta .* d2coskphidt2;

dd2kydt2dkmax = ...
    dd2krdt2dkmax .* sinktheta .* sinkphi + ddkrdtdkmax .* dsinkthetadt .* sinkphi + ddkrdtdkmax .* sinktheta .* dsinkphidt +...
    ddkrdtdkmax .* dsinkthetadt .* sinkphi + dkrdkmax .* d2sinkthetadt2 .* sinkphi + dkrdkmax .* dsinkthetadt .* dsinkphidt +...
    ddkrdtdkmax .* sinktheta .* dsinkphidt + dkrdkmax .* dsinkthetadt .* dsinkphidt + dkrdkmax .* sinktheta .* d2sinkphidt2;

dd2kzdt2dkmax = ...
    dd2krdt2dkmax .* cosktheta + ddkrdtdkmax .* dcoskthetadt +...
    ddkrdtdkmax .* dcoskthetadt + dkrdkmax .* d2coskthetadt2;

dd2kxyzdt2dkmax = [...
    dd2kxdt2dkmax;...
    dd2kydt2dkmax;...
    dd2kzdt2dkmax;...
    ];

dd2kxyzdt2dparam( :, :, 1 ) = dd2kxyzdt2dkmax;

%% partial a
dd2kxdt2da = ...
    dd2krdt2da .* sinktheta .* coskphi + ddkrdtda .* dsinkthetadt .* coskphi + ddkrdtda .* sinktheta .* dcoskphidt +...
    ddkrdtda .* dsinkthetadt .* coskphi + dkrda .* d2sinkthetadt2 .* coskphi + dkrda .* dsinkthetadt .* dcoskphidt +...
    ddkrdtda .* sinktheta .* dcoskphidt + dkrda .* dsinkthetadt .* dcoskphidt + dkrda .* sinktheta .* d2coskphidt2;

dd2kydt2da = ...
    dd2krdt2da .* sinktheta .* sinkphi + ddkrdtda .* dsinkthetadt .* sinkphi + ddkrdtda .* sinktheta .* dsinkphidt +...
    ddkrdtda .* dsinkthetadt .* sinkphi + dkrda .* d2sinkthetadt2 .* sinkphi + dkrda .* dsinkthetadt .* dsinkphidt +...
    ddkrdtda .* sinktheta .* dsinkphidt + dkrda .* dsinkthetadt .* dsinkphidt + dkrda .* sinktheta .* d2sinkphidt2;

dd2kzdt2da = ...
    dd2krdt2da .* cosktheta + ddkrdtda .* dcoskthetadt +...
    ddkrdtda .* dcoskthetadt + dkrda .* d2coskthetadt2;


dd2kxyzdt2da = [...
    dd2kxdt2da;...
    dd2kydt2da;...
    dd2kzdt2da;...
    ];

dd2kxyzdt2dparam( :, :, 2 ) = dd2kxyzdt2da;

%% partial b
dd2kxdt2db = ...
    dd2krdt2db .* sinktheta .* coskphi + ddkrdtdb .* dsinkthetadt .* coskphi + ddkrdtdb .* sinktheta .* dcoskphidt +...
    ddkrdtdb .* dsinkthetadt .* coskphi + dkrdb .* d2sinkthetadt2 .* coskphi + dkrdb .* dsinkthetadt .* dcoskphidt +...
    ddkrdtdb .* sinktheta .* dcoskphidt + dkrdb .* dsinkthetadt .* dcoskphidt + dkrdb .* sinktheta .* d2coskphidt2;

dd2kydt2db = ...
    dd2krdt2db .* sinktheta .* sinkphi + ddkrdtdb .* dsinkthetadt .* sinkphi + ddkrdtdb .* sinktheta .* dsinkphidt +...
    ddkrdtdb .* dsinkthetadt .* sinkphi + dkrdb .* d2sinkthetadt2 .* sinkphi + dkrdb .* dsinkthetadt .* dsinkphidt +...
    ddkrdtdb .* sinktheta .* dsinkphidt + dkrdb .* dsinkthetadt .* dsinkphidt + dkrdb .* sinktheta .* d2sinkphidt2;

dd2kzdt2db = ...
    dd2krdt2db .* cosktheta + ddkrdtdb .* dcoskthetadt +...
    ddkrdtdb .* dcoskthetadt + dkrdb .* d2coskthetadt2;

dd2kxyzdt2db = [...
    dd2kxdt2db;...
    dd2kydt2db;...
    dd2kzdt2db;...
    ];

dd2kxyzdt2dparam( :, :, 3 ) = dd2kxyzdt2db;

%% partial u

dd2kxdt2du = ...
    d2krdt2 .* dsinkthetadu .* coskphi + dkrdt .* ddsinkthetadtdu .* coskphi + dkrdt .* dsinkthetadu .* dcoskphidt +...
    dkrdt .* ddsinkthetadtdu .* coskphi + kr .* dd2sinkthetadt2du .* coskphi + kr .* ddsinkthetadtdu .* dcoskphidt +...
    dkrdt .* dsinkthetadu .* dcoskphidt + kr .* ddsinkthetadtdu .* dcoskphidt + kr .* dsinkthetadu .* d2coskphidt2;

dd2kydt2du = ...
    d2krdt2 .* dsinkthetadu .* sinkphi + dkrdt .* ddsinkthetadtdu .* sinkphi + dkrdt .* dsinkthetadu .* dsinkphidt +...
    dkrdt .* ddsinkthetadtdu .* sinkphi + kr .* dd2sinkthetadt2du .* sinkphi + kr .* ddsinkthetadtdu .* dsinkphidt +...
    dkrdt .* dsinkthetadu .* dsinkphidt + kr .* ddsinkthetadtdu .* dsinkphidt + kr .* dsinkthetadu .* d2sinkphidt2;

dd2kzdt2du = ...
    d2krdt2 .* dcoskthetadu + dkrdt .* ddcoskthetadtdu +...
    dkrdt .* ddcoskthetadtdu + kr .* dd2coskthetadt2du;

dd2kxyzdt2du = [...
    dd2kxdt2du;...
    dd2kydt2du;...
    dd2kzdt2du;...
    ];

dd2kxyzdt2dparam( :, :, 4 ) = dd2kxyzdt2du;

%% partial v

dd2kxdt2dv = ...
    d2krdt2 .* sinktheta .* dcoskphidv + dkrdt .* dsinkthetadt .* dcoskphidv + dkrdt .* sinktheta .* ddcoskphidtdv +...
    dkrdt .* dsinkthetadt .* dcoskphidv + kr .* d2sinkthetadt2 .* dcoskphidv + kr .* dsinkthetadt .* ddcoskphidtdv +...
    dkrdt .* sinktheta .* ddcoskphidtdv + kr .* dsinkthetadt .* ddcoskphidtdv + kr .* sinktheta .* dd2coskphidt2dv;

dd2kydt2dv = ...
    d2krdt2 .* sinktheta .* dsinkphidv + dkrdt .* dsinkthetadt .* dsinkphidv + dkrdt .* sinktheta .* ddsinkphidtdv +...
    dkrdt .* dsinkthetadt .* dsinkphidv + kr .* d2sinkthetadt2 .* dsinkphidv + kr .* dsinkthetadt .* ddsinkphidtdv +...
    dkrdt .* sinktheta .* ddsinkphidtdv + kr .* dsinkthetadt .* ddsinkphidtdv + kr .* sinktheta .* dd2sinkphidt2dv;

dd2kzdt2dv = zeros( size( t ) );

dd2kxyzdt2dv = [...
    dd2kxdt2dv;...
    dd2kydt2dv;...
    dd2kzdt2dv;...
    ];

dd2kxyzdt2dparam( :, :, 5 ) = dd2kxyzdt2dv;

%% convert dd2kxyzdt2dparam to ddGxyzdtdparam
ddGxyzdtdparam = dd2kxyzdt2dparam / s.gyro;

end