function dGxyzdparam = dGxyzdparam_fn( t, s )

%% Initialize derivatives
t = t( : ).';

indenom = indenom_fn( t, s );
denom = denom_fn( t, s );
kr = kr_fn( t, s );
ktheta = ktheta_fn( t, s );
kphi = kphi_fn( t, s );
sinktheta = sin( ktheta );
cosktheta = cos( ktheta );
sinkphi = sin( kphi );
coskphi = cos( kphi );
dkrdt = dkrdt_fn( t, s );
dkthetadt = dkthetadt_fn( t, s );
dkphidt = dkphidt_fn( t, s );
dsinkthetadt = dkthetadt .* cos( ktheta );
dcoskthetadt = -dkthetadt .* sin( ktheta );
dsinkphidt = dkphidt .* coskphi;
dcoskphidt = -dkphidt .* sinkphi;

% kmax
ddkrdtdkmax = ( -s.a .* indenom ) ./ ( s.T .* denom.^2 );
dkrdkmax = 1 ./ denom;

% a
ddkrdtda = - ( ( 1 ) ./ ( s.T^2 * denom.^3 ) )...
    .* ( ( s.kmax * indenom ) .*...
    ( ( -s.a * t ) .* indenom ...
    + ( s.a * s.b * s.T ) * indenom...
    + s.T * indenom ...
    - ( s.a * s.b * s.T ) + s.a * t + s.T ) );
dkrda = ( -s.kmax * ( ( t/s.T - s.b ) .* indenom ) ) ./ ( denom.^2 );

% b
ddkrdtdb = ( ( - s.a^2 * s.kmax ) * ( indenom .* ( indenom - 1 ) ) ) ./ ( s.T * denom.^3 );
dkrdb = ( ( s.kmax * s.a ) .* indenom ) ./ ( denom.^2 );

% u
dsinkthetadu = t .* cos( ktheta );
ddsinkthetadtdu = cosktheta - s.u * ( t .* sinktheta );

dcoskthetadu = -t .* sin( ktheta );
ddcoskthetadtdu = - sinktheta - s.u * ( t .* cosktheta );

% v
dsinkphidv = t .* coskphi;
ddsinkphidtdv = coskphi - s.v * ( t .* sinkphi );

dcoskphidv = -t .* sinkphi;
ddcoskphidtdv = - sinkphi - s.v * ( t .* coskphi );

ddkxyzdtdparam = zeros( 3, length( t ), 5 );

%% partial kmax

ddkxdtdkmax = ...
    ddkrdtdkmax .* sinktheta .* coskphi + ...
    dkrdkmax .* dsinkthetadt .* coskphi + ...
    dkrdkmax .* sinktheta .* dcoskphidt;

ddkydtdkmax = ...
    ddkrdtdkmax .* sinktheta .* sinkphi + ...
    dkrdkmax .* dsinkthetadt .* sinkphi + ...
    dkrdkmax .* sinktheta .* dsinkphidt;

ddkzdtdkmax = ...
    ddkrdtdkmax .* cosktheta + ...
    dkrdkmax .* dcoskthetadt;

ddkxyzdtdkmax = [...
    ddkxdtdkmax;...
    ddkydtdkmax;...
    ddkzdtdkmax;...
    ];

ddkxyzdtdparam( :, :, 1 ) = ddkxyzdtdkmax;

%% partial a

ddkxdtda = ...
    ddkrdtda .* sinktheta .* coskphi + ...
    dkrda .* dsinkthetadt .* coskphi + ...
    dkrda .* sinktheta .* dcoskphidt;

ddkydtda = ...
    ddkrdtda .* sinktheta .* sinkphi + ...
    dkrda .* dsinkthetadt .* sinkphi + ...
    dkrda .* sinktheta .* dsinkphidt;

ddkzdtda = ...
    ddkrdtda .* cosktheta + ...
    dkrda .* dcoskthetadt;

ddkxyzdtda = [...
    ddkxdtda;...
    ddkydtda;...
    ddkzdtda;...
    ];

ddkxyzdtdparam( :, :, 2 ) = ddkxyzdtda;

%% partial b

ddkxdtdb = ...
    ddkrdtdb .* sinktheta .* coskphi + ...
    dkrdb .* dsinkthetadt .* coskphi + ...
    dkrdb .* sinktheta .* dcoskphidt;

ddkydtdb = ...
    ddkrdtdb .* sinktheta .* sinkphi + ...
    dkrdb .* dsinkthetadt .* sinkphi + ...
    dkrdb .* sinktheta .* dsinkphidt;

ddkzdtdb = ...
    ddkrdtdb .* cosktheta + ...
    dkrdb .* dcoskthetadt;

ddkxyzdtdb = [...
    ddkxdtdb;...
    ddkydtdb;...
    ddkzdtdb;...
    ];

ddkxyzdtdparam( :, :, 3 ) = ddkxyzdtdb;

%% partial u

ddkxdtdu = ...
    dkrdt .* dsinkthetadu .* coskphi + ...
    kr .* ddsinkthetadtdu .* coskphi + ...
    kr .* dsinkthetadu .* dcoskphidt;

ddkydtdu = ...
    dkrdt .* dsinkthetadu .* sinkphi + ...
    kr .* ddsinkthetadtdu .* sinkphi + ...
    kr .* dsinkthetadu .* dsinkphidt;

ddkzdtdu = ...
    dkrdt .* dcoskthetadu + ...
    kr .* ddcoskthetadtdu;

ddkxyzdtdu = [...
    ddkxdtdu;...
    ddkydtdu;...
    ddkzdtdu;...
    ];

ddkxyzdtdparam( :, :, 4 ) = ddkxyzdtdu;

%% partial v

ddkxdtdv = ...
    dkrdt .* sinktheta .* dcoskphidv + ...
    kr .* dsinkthetadt .* dcoskphidv + ...
    kr .* sinktheta .* ddcoskphidtdv;

ddkydtdv = ...
    dkrdt .* sinktheta .* dsinkphidv + ...
    kr .* dsinkthetadt .* dsinkphidv + ...
    kr .* sinktheta .* ddsinkphidtdv;

ddkzdtdv = zeros( size( t ) );

ddkxyzdtdv = [...
    ddkxdtdv;...
    ddkydtdv;...
    ddkzdtdv;...
    ];

ddkxyzdtdparam( :, :, 5 ) = ddkxyzdtdv;

%% convert dd2kxyzdt2dparam to ddGxyzdtdparam
dGxyzdparam = ddkxyzdtdparam / s.gyro;

end