function [ partialfpartialGfall_real, partialfpartialGfall_imag ] = calculatepartialfpartialG_MPSP_fall(...
    partialfpartialBz, wv, opt, ti )

partBpartGmagi = ( -( ti - wv.tEndMPSP ) / wv.MPSPGradSlewTime ) *...
    cos( wv.wz_mpptx * ( wv.tEndMPSP - wv.tStMPSP - wv.MPSPGradSlewTime ) + wv.G_ph_MPSP );
partBpartGphi = ( ( ti - wv.tEndMPSP ) / wv.MPSPGradSlewTime ) * wv.G_mag_MPSP .*...
    sin( wv.wz_mpptx * ( wv.tEndMPSP - wv.tStMPSP - wv.MPSPGradSlewTime ) + wv.G_ph_MPSP );

[ partialfpartialGfall_real, partialfpartialGfall_imag ] = calculatepartialfpartialG_MPSP(...
    partialfpartialBz, partBpartGmagi, partBpartGphi, wv, opt );

end