function partialfpartialbimag_MPSP = calcpartialfpartialbimag_MPSP(...
    partialfpartialBx, partialfpartialBy, opt, b1prealcos, b1pimagsin, b1prealsin, b1pimagcos )

partialfpartialbimag_MPSP = ...
    partialfpartialBx .* reshape( -( b1prealsin + b1pimagcos ), [opt.numPos, 1, opt.numXYCoils] ) +...
    partialfpartialBy .* reshape( ( b1prealcos - b1pimagsin ), [opt.numPos, 1, opt.numXYCoils] );

end