function partialfpartialbreal_MPSP = calcpartialfpartialbreal_MPSP(...
    partialfpartialBx, partialfpartialBy, opt, b1prealcos, b1pimagsin, b1prealsin, b1pimagcos )

    partialfpartialbreal_MPSP = ...
        partialfpartialBx .* reshape( ( b1prealcos - b1pimagsin ), [ opt.numPos, 1, opt.numXYCoils] ) +...
        partialfpartialBy .* reshape( ( b1pimagcos + b1prealsin ), [ opt.numPos, 1, opt.numXYCoils] );

end