function [ partialfpartialbreal_MPSP_const, partialfpartialbimag_MPSP_const ] = calcpartialfpartialb_MPSP_const(...
    b1prealcos, b1pimagsin, b1prealsin, b1pimagcos, sc, partialfpartialBx, partialfpartialBy, opt )

partialfpartialbreal_MPSP_const = ...
        sc * (...
        partialfpartialBx .* reshape( ( b1prealcos - b1pimagsin ), [ opt.numPos, 1, opt.numXYCoils] ) +...
        partialfpartialBy .* reshape( ( b1pimagcos + b1prealsin ), [ opt.numPos, 1, opt.numXYCoils] ) );

partialfpartialbimag_MPSP_const = ...
    sc * ( ...
    partialfpartialBx .* reshape( -( b1prealsin + b1pimagcos ), [ opt.numPos, 1, opt.numXYCoils ] ) +...
    partialfpartialBy .* reshape( ( b1prealcos - b1pimagsin ), [ opt.numPos, 1, opt.numXYCoils ] ) );

end