function optNew = addOptInfoNewFieldStruct( optOld )
% Initialize the new structure
optNew = struct;

% Define list of field names as a cell array for compatibility with isfield
listOfFieldnames = {...
    'structtype';...
    'di';...
    'dt';...

    'x';...
    'y';...
    'z';...

    'X';...
    'Y';...
    'Z';...

    'constantRotatingFrame';...
    'timing_dwxy';...
    'vals_dwxy';...
    'convertMBackToLarmor';...
    'convertMtargAwayLarmor';...

    'VOPs';...
    'numVOPs';...
    'QGlobal';...

    'bzsens';...
    'b1preal';...
    'b1pimag';...
    'db0';...
    'pos';...
    'M0';...
    'Mtarg';...
    'idx';...
    'optroi';...
    'zi';...
    'gyro';...
    'numPos';...
    'numPosSubj';...
    'cum_numPosSubj';...
    'subjIden';...
    'subjPath';...

    'numZCoils';...
    'numXYCoils';...
    'numSubj';...

    'dwxy';...
    'dfxy';...
    'mdfxy';...
    'mdwxy';...
    'timing_dfxy';...
    'timing_dwxy';...
    'vals_dwxy';...
    'vals_dfxy';...
    'constantRotatingFrame';...
    'convertMBackToLarmor';...
    'convertMtargAwayLarmor';...

    'useGPU';...

    'p0';...
    'pSc0';...

    'initOptTime';...

    'RF0';...
    'G0';...
    'K0';...
    'spokes';...



    % 'numTimePoints';...
    % 'tvec';...
    % 'dtvec';...
    % 'pulseLength';...
    % 'opt_tvec';...
    % 'opt_dtvec';...
    % 'dwxyvec';...
    % 
    % 'varNames';...
    % 'varAmts';...
    % 'varNumDictionary';...
    % 'varCumSum';...
    % 'varIdxs';...
    % 'numVars';...
    % 'estMaxActiveVarsTimeStep';...
    % 
    % 'scVec';...
    % 'ub';...
    % 'lb';...
    % 'Z0';...
    % 'dutyCycle';...
    % 
    % 'RFMax_constr';...
    % 'gradMax_constr';...
    % 'shimMax_constr';...
    % 'totalRFPower_constr';...
    % 'maxRFPower_constr';...
    % 'peakLocalSAR_constr';...
    % 'peakGlobalSAR_constr';...
    % 'avgLocalSAR_constr';...
    % 'avgGlobalSAR_constr';...
    % 'RFBandwidth_band';...
    % 'RFBandwidth_constr';...
    % 'RFSlewRate_constr';...
    % 'RFAccel_constr';...
    % 'gradSlewRate_constr';...
    % 'gradAccel_constr';...
    % 'shimSlewRate_constr';...
    % 'shimAccel_constr';...
    % 'shimTotal_constr';...
    % 'gradMaxMPSP_constr';...
    % 'gradBlipMax_constr';...
    % 'shimMaxMPSP_constr';...
    % 'shimBlipMax_constr';...
    % 
    % 'A';...
    % 'b';...
    % 'AbConstraintNames';...
    % 'AbConstraintAmts';...
    % 'AbConstraintCumSum';...
    % 'Aeq';...
    % 'beq';...
    % 'AbeqConstraintNames';...
    % 'AbeqConstraintAmts';...
    % 'AbeqConstraintCumSum';...
    % 'nlconIneqFuncs';...
    % 'nlconIneqFuncNames';...
    % 'nlconIneqAmts';...
    % 'nlconIneqCumSum';...
    % 'nlconEqFuncs';...
    % 'nlconEqFuncNames';...
    % 'nlconEqAmts';...
    % 'nlconEqCumSum';...
    % 'nonlcon';...
    % 
    % 'generateWaveforms';...
    % 'generatePlotWaveforms';...
    % 'forwardModelGradientFunction';...
    % 'postProcessFunction';...
    % 'gpuArrayAdjointFunction';...
    % 
    % 
    % '';...
    % '';...
    % '';...
    % '';...
    % '';...
    % '';...
    % '';...
    % '';...

    };

% Check if optOld has the field 'varNames'
if isfield(optOld, 'varNames') && isstring(optOld.varNames)
    % Append each varName with "_idx" to listOfFieldnames
    for jj = 1:length(optOld.varNames)
        listOfFieldnames{end+1} = optOld.varNames(jj) + "_idx"; %#ok
    end
end

% Get all field names from optOld
optOldFieldnames = fieldnames(optOld);

% Iterate through field names and copy if present in optOld
for ii = 1:length(listOfFieldnames)
    fieldName = listOfFieldnames{ii};

    % Check for exact match or possible misspellings
    matchIdx = find(strcmp(optOldFieldnames, fieldName), 1);

    if ~isempty(matchIdx)
        % Use the correctly spelled field name from optOld
        correctFieldName = optOldFieldnames{matchIdx};
        optNew.(correctFieldName) = optOld.(correctFieldName);
        % fprintf('Field "%s" successfully copied.\n', correctFieldName);
    else
        % fprintf('Warning: Field "%s" not found in optOld. Check spelling.\n', fieldName);
    end
end
end
