function partialBpartialShimCheb = calcpartialBpartialShimCheb( partialfpartialBz, opt, wv, nn )

% partial w.r.t shim
% partialBzpartialshimcheb = reshape(...
%     wv.Tn( nn, : ) .* reshape( wv.bzsens, [opt.numPos, 1, opt.numZCoils ] ),...
%     [ opt.numPos, 1, opt.numCheb_shim*opt.numZCoils ] );
% 
% partialBpartialShimCheb =...
%     partialfpartialBz .* partialBzpartialshimcheb;

partialBpartialShimCheb =...
    partialfpartialBz .* reshape(...
    wv.Tn( nn, 1:opt.numCheb_shim ) .* reshape( wv.bzsens, [opt.numPos, 1, opt.numZCoils ] ),...
    [ opt.numPos, 1, opt.numCheb_shim*opt.numZCoils ] );

% clear partialBzpartialshimcheb;

end