function partialBpartialGradCheb = calcpartialBpartialGradCheb( partialfpartialBz, opt, wv, nn )

% partial w.r.t grad
% partialBzpartialgradcheb = reshape(...
%     Tnttrep .* reshape( wv.pos, [ opt.numPos, 1, 3 ] ),...
%     [ opt.numPos, 1, opt.numCheb_grad * 3 ] );
% 
% partialBpartialGradCheb =...
%     partialfpartialBz .* partialBzpartialgradcheb;

partialBpartialGradCheb =...
    partialfpartialBz .* reshape(...
    wv.Tn( nn, 1:opt.numCheb_grad ) .* reshape( wv.pos, [ opt.numPos, 1, 3 ] ),...
    [ opt.numPos, 1, opt.numCheb_grad * 3 ] );

% clear partialBzpartialgradcheb;

end