function [ magNRMSE_Mxy, NRMSE_Mxy, magNRMSE_FA,...
    meanFA, stdFA, nMaxMin, magCoeffVar ] = ...
    calculateFAMtargMetrics( Mopt, FAopt, Mtarg, FAtarg )

magNRMSE_Mxy = norm(...
        sqrt( Mopt( :, 1 ).^2 + Mopt( :, 2 ).^2 )...
        - sqrt( Mtarg( :, 1 ).^2 + Mtarg( :, 2 ).^2 ) )...
        / norm( sqrt( Mtarg( :, 1 ).^2 + Mtarg( :, 2 ).^2 ) );

NRMSE_Mxy = norm(...
    sqrt( ( Mopt( :, 1 ) - Mtarg( :, 1 ) ).^2 ...
    + ( Mopt( :, 2 ) - Mtarg( :, 2 ) ).^2 ) )...
    / norm( sqrt( Mtarg( :, 1 ).^2 + Mtarg( :, 2 ).^2 ) );

magNRMSE_FA = norm( FAopt - FAtarg ) /norm( FAtarg );

meanFA = mean( FAopt );

stdFA = std( FAopt );

nMaxMin = ( max( FAopt ) - min( FAopt ) ) / mean( FAopt );

magCoeffVar = std( FAopt ) / mean( FAopt );

end