function [ partialfpartialbrealshape, partialfpartialbimagshape ] = calcpartialBpartialRFPP(...
    partialfpartialBx, partialfpartialBy, ShapeFnValrep, opt, wv  )

b1preal_rshp = reshape( wv.b1preal, [opt.numPos, 1, opt.numXYCoils] );
b1pimag_rshp = reshape( wv.b1pimag, [opt.numPos, 1, opt.numXYCoils] );

% partial w.r.t breal
numActiveSF = size(ShapeFnValrep,2);

partialBxpartialbrealshape = reshape(...
    ShapeFnValrep .* b1preal_rshp,...
    [ opt.numPos, 1, numActiveSF*opt.numXYCoils ] );
partialBypartialbrealshape = reshape(...
    ShapeFnValrep .* b1pimag_rshp,...
    [ opt.numPos, 1, numActiveSF*opt.numXYCoils ] );

partialfpartialbrealshape =...
    partialfpartialBx .* partialBxpartialbrealshape +...
    partialfpartialBy .* partialBypartialbrealshape;

% clear partialBxpartialbrealcheb partialBypartialbrealcheb;

% partial w.r.t bimag
partialBxpartialbimagcheb = reshape(...
    ShapeFnValrep .* -b1pimag_rshp,...
    [ opt.numPos, 1, numActiveSF*opt.numXYCoils ] );
partialBypartialbimagcheb = reshape(...
    ShapeFnValrep .* b1preal_rshp,...
    [ opt.numPos, 1, numActiveSF*opt.numXYCoils ] );

partialfpartialbimagshape =...
    partialfpartialBx .* partialBxpartialbimagcheb +...
    partialfpartialBy .* partialBypartialbimagcheb;

% clear partialBxpartialbimagcheb partialBypartialbimagcheb;

end